<?php
if( function_exists('register_field_group') ):

$options_page_sidebar_acf = array(
  'key' => 'options_group_sidebar',
  'title' => 'Site Overides',
  'fields' => array (
    array (
      'key' => 'sidebar_boolean',
      'label' => '',
      'name' => 'enable_sidebar',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => 'Enable the sidebar',
      'default_value' => 1,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options',
      ),
      array (
        'param' => 'current_user_role',
        'operator' => '==',
        'value' => 'administrator',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
);

$options_page_sidebar_acf = apply_filters('agreable_base_theme_options_page_sidebar_acf', $options_page_sidebar_acf);
register_field_group($options_page_sidebar_acf);

$options_page_settings_acf = array(
  'key' => 'options_group_settings',
  'title' => 'Tracking, Data & Third Party settings',
  'fields' => array (
    array (
      'key' => 'options_google_analytics_id',
      'label' => 'Google Analytics ID',
      'name' => 'google_analytics_id',
      'prefix' => '',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'options_calais_passport_id',
      'label' => 'Calais Passport ID',
      'name' => 'calais_passport_id',
      'prefix' => '',
      'type' => 'text',
      'instructions' => 'Required for sign-up form. Contact Digital Operations if not present.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'options_calais_passport_secret',
      'label' => 'Calais Passport Secret',
      'name' => 'calais_passport_secret',
      'prefix' => '',
      'type' => 'text',
      'instructions' => 'Required for sign-up form. Contact Digital Operations if not present.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options',
      ),
    ),
  ),
  'menu_order' => 1,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
);

$options_page_settings_acf = apply_filters('agreable_base_theme_options_page_settings_acf', $options_page_settings_acf);
register_field_group($options_page_settings_acf);

$options_page_branding_acf = array(
  'key' => 'options_group_branding',
  'title' => 'Branding',
  'fields' => array (
    array (
      'key' => 'branding_favicon_ico',
      'label' => 'Favicon (.ico file)',
      'name' => 'favicon_ico',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => 'ico',
    ),
    array (
      'key' => 'branding_favicon_png',
      'label' => 'Favicon (.png file)',
      'name' => 'favicon_png',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'full',
      'library' => 'all',
      'min_width' => 16,
      'min_height' => 16,
      'min_size' => '',
      'max_width' => 256,
      'max_height' => 256,
      'max_size' => '',
      'mime_types' => 'png',
    ),
    array(
      'key' => 'branding_primary_colour',
      'label' => 'Brand Primary Colour',
      'name' => 'primary_colour',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
    ),
    array (
      'key' => 'branding_login_image',
      'label' => 'Wordpress Login Image',
      'name' => 'login_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options',
      ),
    ),
  ),
  'menu_order' => 2,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
);
$options_page_branding_acf = apply_filters('agreable_base_theme_options_page_branding_acf', $options_page_branding_acf);
register_field_group($options_page_branding_acf);

$options_page_social_media_acf = array (
  'key' => 'options_group_social_media',
  'title' => 'Social Media',
  'fields' => array (
    array (
      'key' => 'social_media_default_share',
      'label' => 'Default share image',
      'name' => 'default_share_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'full',
      'library' => 'all',
      'min_width' => 1200,
      'min_height' => 630,
      'min_size' => '',
      'max_width' => 3000,
      'max_height' => 1000,
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'social_media_facebook_page_url',
      'label' => 'Facebook Page (URL)',
      'name' => 'facebook_page_url',
      'type' => 'url',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
    ),
    array (
      'key' => 'social_media_twitter_id',
      'label' => 'Twitter Handle / ID',
      'name' => 'twitter_id',
      'type' => 'text',
      'instructions' => 'Do not include the @ symbol',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'social_media_facebook_app_id',
      'label' => 'Facebook App ID',
      'name' => 'facebook_app_id',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options',
      ),
    ),
  ),
  'menu_order' => 3,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
);

$options_page_social_media_acf = apply_filters('agreable_base_theme_options_page_social_media_acf', $options_page_social_media_acf);
register_field_group($options_page_social_media_acf);

endif;
